### ISSUE TITLE
add specific url when browsing different networks

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/nodes-explorer#1]
https://explorer.threefold.io/

at the moment the url shows explorer.threefold.io regardless which network I'm seeing. 

as a user when I click on 'testnet' on filter and being shown testnet nodes, I would like a URL that specifies this. so that I can share this link to others. maybe something like explorer.threefold.io/testnet or something like that.

**Comment by DylanVerstraete** [comment]
Added in: https://github.com/threefoldtech/nodes-explorer/commit/3fc85d1eb4b87e4fe3bbf9b5fb1f380dc1b7f369

**Comment by DylanVerstraete** [comment]
Redeployed as well:

Link to test: https://explorer.threefold.io/testnet
