### ISSUE TITLE
add dropdown items and links to v3 explorer

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/nodes-explorer#17]
All in one: https://explorer.threefold.io/

Dropdown:

V2 testnet
V2 mainnet

V3 testnet
V3 mainnet

Now: 
￼
<img width="381" alt="image" src="https://user-images.githubusercontent.com/18591016/149925750-fd7edd1d-dd9a-4966-8d0c-c7f975712337.png">

Link from this explorer to 

State ‘Link to V3 Mainnet Explorer’
Link to  https://portal.grid.tf/explorer or create button with link behind

State ‘Link to V3 Testnet Explorer’
Link to https://portal.test.grid.tf/explorer or create button with link behind

**Comment by dmahmouali** [comment]
duplicated with https://github.com/threefoldtech/nodes-explorer/issues/12
