### ISSUE TITLE
make all networks as default view

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/nodes-explorer#18]
**https://explorer.threefold.io/** 

- [x] when i go to https://explorer.threefold.io/ first time, As a user I would like to see **grid3 , all net**  on the overview page.as default view, not testnet as default view.

<img width="1438" alt="Screenshot 2022-01-27 at 16 00 20" src="https://user-images.githubusercontent.com/43240801/151384722-a6c3d083-583a-4527-8ad6-04f760a1e8f0.png">

**Comment by andhartl** [comment]
Checked all links and values. some of the values are still off. see my file: https://docs.google.com/spreadsheets/d/1yrjfBWl90wac9peqCA3F3Kk6x6vU_ZSnN_jJpS9C0tI/edit#gid=0

**Comment by dmahmouali** [comment]
the redirection issue is fixed and the values conflict will be tracked in this issue: https://github.com/threefoldtech/tfchain_explorer/issues/153
