### ISSUE TITLE
In the v2 & v3 combined view, most v3 nodes are reported twice

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/nodes-explorer#27]
This leads to resources and online nodes being way to high. Also see #25. At the time of writing, the reported values are:

![image](https://user-images.githubusercontent.com/22023708/159713925-c5062941-6486-4683-9637-8b0c63703a7e.png)

whereas only showing results for grid V3:

![image](https://user-images.githubusercontent.com/22023708/159714061-6731e374-0f9b-4a89-910b-02df57a8e8b5.png)

and grid V2:

![image](https://user-images.githubusercontent.com/22023708/159714179-23ab9039-96e1-4331-a49d-9205e9f39bbc.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/nodes-explorer/pull/28
