### ISSUE TITLE
Add message to webpage for migration

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/nodes-explorer#29]
There needs to be a message reminding farmers that they need to migrate to v3.

"Make sure to [migrate your v2 nodes](https://forum.threefold.io/t/farming-migration-grid-v2-v3/2143) to TF Grid v3 before May 1st 2022. The [v2 explorer](https://explorer.grid.tf/) will no longer be supported after that date."

Message should be very present & noticeable. 

Thanks!

**Comment by scottyeager** [comment]
Let's remove the banner since this date has passed and is now confusing. https://github.com/threefoldfoundation/home/issues/224

**Comment by rkhamis** [comment]
message now says "Our resources are solely going to development on Grid v3. Please make sure to [migrate](https://forum.threefold.io/t/farming-migration-grid-v2-v3/2143) your farm/nodes. You can find the grid 3 explorer [here](https://explorer3.grid.tf/)."
