### ISSUE TITLE
"V3 Compliant" is confusing for farmers

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/nodes-explorer#6]
Farmers are seeing a red X next to "V3 Compliant", causing confusion or worry that the farm is somehow deficient.

Suggest to:
1. Change message to say "V3 Minting Activated"
2. Provide a link to wiki on V3 logic

**Comment by DylanVerstraete** [comment]
done

**Comment by scottyeager** [comment]
Thank you :pray:
